### ISSUE TITLE
Add a method to toggle play/pause state

### ISSUE THREAD

**Issue by ludelafo** [2find/stereo#16]
The library should be able to play/pause an audio file.

When an audio file is playing, calling this method should pause the audio file and when an audio file is in pause, calling this method should play/resume the audio file.

I see the following method:
- `void togglePlaying()` - toggle the play/pause state

This method should throw an exception if the audio file can't have its play/pause state changed.

**Comment by faku99** [comment]
I think that a `void togglePlaying()` method is useless since we already have `play()` and `pause()` methods.

IMO, the best would be to add a `bool isPlaying()` method and let the developer implements a method that toggles the state as he wishes. What do you think about that?

**Comment by ludelafo** [comment]
@faku99 I agree, it would be way easier!
