### ISSUE TITLE
Add a method to unload an audio file

### ISSUE THREAD

**Issue by ludelafo** [2find/stereo#23]
The library should be able to unload an audio file.
I see the following method:

- `void unload()` - unload the audio file

This method should throw an exception if the audio file can't be unloaded.

**Comment by ludelafo** [comment]
I was wondering if the `load` and `unload` methods were needed if we changed the `play` method to accept string, URI or AudioFile parameters. What would be the benefits to have these two methods?

**Comment by faku99** [comment]
Calling the method `stop()` already unloads the file from the player. I'm closing this issue since this method is not needed.
