### ISSUE TITLE
Add a method that shows an UI to pick an audio file from storage

### ISSUE THREAD

**Issue by faku99** [2find/stereo#26]
The library should be able to show a simple UI to pick an audio file from storage.

I think of the following method signature:
* `Future<AudioFile> showPicker()` - opens a simple picker for an audio file. The type `AudioFile` is the same as defined in #8.

**Comment by faku99** [comment]
I just thought of something so I'm writing it down here. I'll talk about it as an Android implementation since you guys know how it works.

I don't know if that's even possible with the current state of Flutter but it would be interesting to find a way to pass an `Intent` (or something similar) to the constructor of our Android plugin (from a class that a developer which uses stereo has created) so it calls this `Intent`.
By default, if the constructor parameter is `null`, then it will use our default implementation.

What do you guys think about that? Tell me if something isn't clear or if you disagree. If not, I'll do some research.

**Comment by faku99** [comment]
As the above commit shows, I started working on the UI picker (only for Android atm).

I defined a new method for stereo: `Future<String> picker()` (btw we might want to change the name, I don't really like it). Currently, it shows the UI picker and returns the path of the audio file the user picked or `null` if no valid file was picked.

But a question came to my mind (related to #8): should we carry on with the current behaviour and offer a new method e.g. `Future<AudioTrack> getMetadata(String uri)` or should we modify the `picker()` method to `Future<AudioTrack> picker()` and return metadata directly?

**Comment by ludelafo** [comment]
@faku99 I might not see the big picture but what would be the advantages/propose of such functionality ?

**Comment by ludelafo** [comment]
@faku99 I think we could directly have the metadata from the chosen file so you could use these information right away.

**Comment by faku99** [comment]
@ludelafo Honestly, I don't see any pros to have the two methods except to offer more flexibility to users
