### ISSUE TITLE
background play available??

### ISSUE THREAD

**Issue by praveendp526** [2find/stereo#31]
will it play in background?? even if we are moving to other page??

**Comment by faku99** [comment]
Yes, I can confirm it works with `Navigator.push()` and `Navigator.pop()`.

**Comment by faku99** [comment]
The same goes for when leaving the app or locking the phone.

**Comment by cwrogers** [comment]
I'm using iOS 11.2 and am not able to get music to play in the background.  Navigator.push/pop causes no issue but leaving the app/locking the screen is causing the audio to stop. 

Edit: Nevermind, it was my own error. Sorry

**Comment by faku99** [comment]
Closing the issue according to @cwrogers edit.
