### ISSUE TITLE
Need some cleanup in repo

### ISSUE THREAD

**Issue by ludelafo** [2find/stereo#4]
I think we need to cleanup some files and code lines.

For example, in [the following classes](https://github.com/2find/stereo/tree/master/ios/Classes), `MCMediaPickerController.h` and `MCMediaPickerController.m` use the word `MC`, which was our first organization's name.

And [here](https://github.com/2find/stereo/tree/master/lib), `audio_player` is still used.

Shouldn't we rename all of these to relate more to `stereo` (if `stereo` is definitive ?) ? I haven't checked all the repo, at the moment.

**Comment by faku99** [comment]
I don't know. Even if the library is named **stereo**, the class still represents an audio player, which is why I kept the old name.

About the class `MCMediaPickerController`, it will be removed when I'll take care of #3.

**Comment by ludelafo** [comment]
I think of `stereo` more as an abstraction to interact with the native audio capabilities of the platforms than a real audio player. It certainly can play music, but it doesn't act like a real audio player for me. That's why it's a bit ambiguous in my opinion.

But we can always change it later !

**Comment by faku99** [comment]
You are totally right. I'll change it right away.

**Comment by ludelafo** [comment]
As we have discussed today, I think we should organize the repository as follow:

- Move all the sources files to a specific folder `src/`
- Create a folder `docs/` for future documentation
- Leave the `example/` at the root of the repository to show a way to use the library
- Create a new `README.md` at the root of the repository for the following points:
  - General proposes of the library
  - How is the repository is organized
  - Where to find the resources (Wiki links, documentation, examples, etc.)

**Comment by faku99** [comment]
I just made some changes concerning the repository re-organization. Please confirm that it's good for you
