### ISSUE TITLE
Add a class that represents a song

### ISSUE THREAD

**Issue by faku99** [2find/stereo#8]
First of all, what should we name it? I was thinking of something like `Track`, `Song`, `StereoItem`, `MediaItem`. Please let me know if you have other ideas.

What information should this class hold? Here are some thoughts:
* Title
* Artist
* Album
* URI
* Length
* Artwork URI

**Comment by ludelafo** [comment]
I think we should have two (or more) classes.
- The first one would represents an `AudioFile`. We don't care more about it, it's just an audio file that needs to be read. We could get the following information:
  - URI
  - Length
- The second one would be an `AudioTrack`, from which we should get the following information:
  - Title
  - Artist
  - Album
  - Artwork URI

**Comment by ludelafo** [comment]
How would we get the metadata from the audio file ? Would we need an external library to read the file and return the AudioTrack object or do we get the metadata from the OS ?
